books/urls.py
from django.urls import path

from books.views import BooksView, BookDetailView

app_name = "books"

urlpatterns = [
    path("", BooksView.as_view(), name="books_list"),
    path("detils/<int:year>/<int:month>/<int:day>/<slug:slug>/", BookDetailView.as_view(), name="book_detail")
]

goodreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from goodreads import settings
from goodreads.views import NotFoundView, HomeView, LandingView

handler404 = NotFoundView.as_view()


urlpatterns = [
    path("", LandingView.as_view(), name="landing"),
    path("home/", HomeView.as_view(), name="home"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),


    path("admin/", admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, UpdateProfileView

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name='login'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("update_profile/", UpdateProfileView.as_view(), name="update_profile")
]

templates/base.html
{% load static %}

{% url "home" as home_url %}
{% url "landing" as landing_url %}
{% url "books:books_list" as books_url %}
{% url "users:profile" as profile_url %}
{% url "users:update_profile" as update_profile_url %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads Clone{% endblock title %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

<nav class="bg-white border-gray-200 dark:bg-gray-900">
    <div class="max-w-screen-xl border-b flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url "landing" %}" class="text-xl font-semibold">
            Goodreads Clone</a>

        <div class="items-center justify-between hidden w-full md:flex md:w-auto" id="navbar-language">
            <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <a href="{% url "landing" %}"
                       class="{% if request.path == landing_url %}text-blue-700{% endif %} block py-2 px-3 rounded"
                       aria-current="page">Landing</a>
                </li>
                <li>
                    <a href="{% url "home" %}"
                       class="{% if request.path == home_url %}text-blue-700{% endif %} block py-2 px-3 rounded"
                       aria-current="page">Home</a>
                </li>
                <li>
                    <a href="{% url "books:books_list" %}"
                       class="{% if request.path == books_url %}text-blue-700{% endif %} block py-2 px-3 rounded md:bg-transparent"
                       aria-current="page">Books</a>
                </li>
            </ul>
        </div>
        <div class="flex relative items-center space-x-1 md:space-x-0 rtl:space-x-reverse">
            {% if not request.user.is_authenticated %}
                <a class="font-medium text-blue-500 px-4 py-2 text-sm text-gray-900 dark:text-white rounded-lg cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white"
                   href="{% url "users:login" %}">Login</a>
                <a class="font-medium px-4 py-2 text-sm text-gray-900 dark:text-white rounded-lg cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white"
                   href="{% url "users:register" %}">Register</a>
            {% else %}
                <button type="button" data-dropdown-toggle="language-dropdown-menu"
                        id="drop_down_btn"
                        class="{% if request.path == profile_url or request.path == update_profile_url %}text-blue-500{% else %} text-gray-500{% endif %} font-medium px-4 py-2 text-sm dark:text-white rounded-lg cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-white">
                    {{ request.user.username }}
                </button>
                <div id="drop_down_close" class="hidden fixed inset-0 z-40"></div>
                <!-- Dropdown -->
                <div id="drop_down"
                     class="z-50 right-0 top-full absolute hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700">
                    <ul class="py-2 font-medium" role="none">
                        <li>
                            <a href="{% url "users:profile" %}"
                               class="block px-4 text-nowrap py-2 mx-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                               role="menuitem">
                                Profile
                            </a>
                        </li>

                        <li>
                            <a href="{% url "users:logout" %}"
                               class="block px-4 text-nowrap py-2 mx-2 text-sm text-red-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                               role="menuitem">
                                Log out
                            </a>
                        </li>

                    </ul>
                </div>
            {% endif %}

        </div>

    </div>
</nav>


<div class="max-w-screen-xl mx-auto p-4">
    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}
    {% block content %} {% endblock content %}
</div>
<script src={% static "js/main.js" %}></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}
    <h1 class="text-2xl font-semibold">All reviews</h1>
    {% if page_obj %}
        <div class="grid mt-6 grid-cols-3 gap-8">
            {% for review in page_obj.object_list %}
                <div class="flex flex-col justify-start w-full h-full p-8 bg-gray-100 dark:bg-gray-800 rounded-2xl dark:bg-trueGray-800">
                    <div class="flex items-center mb-8 space-x-3">
                        <img class="flex-shrink-0 object-cover overflow-hidden rounded-full w-14 h-14" alt="profile picture"
                             src="{{ review.user.profile_picture.url }}"
                             loading="lazy"/>
                        <div>
                            <div class="text-lg font-medium text-indigo-500">{{ review.user.username }}</div>
                            <div class="text-gray-600 dark:text-gray-400 text-sm">{{ review.created_time | date:"M d, Y" }}</div>
                        </div>
                    </div>
                    <p>
                        {{ review.comment | truncatewords:60 }}
                    </p>
                </div>
            {% endfor %}
        </div>

        <div class="flex items-center gap-x-1 mt-8">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}"
                   class="min-h-[38px] min-w-[38px] py-2 px-2.5 inline-flex justify-center items-center gap-x-1.5 text-sm rounded-lg text-gray-800 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none"
                   disabled="">
                    <svg class="flex-shrink-0 size-3.5" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path d="m15 18-6-6 6-6"></path>
                    </svg>
                    <span>Previous</span>
                </a>
            {% endif %}

            <div class="flex items-center gap-x-1">

                {% for page_number in page_obj.paginator.page_range %}
                    <a href="?page={{ page_number }}"
                       class="{% if page_number == page_obj.number %}bg-gray-200{% endif %} min-h-[38px] min-w-[38px] flex justify-center items-center text-gray-800 py-2 px-3 text-sm rounded-lg focus:outline-none hover:bg-gray-300 disabled:opacity-50 disabled:pointer-events-none"
                       aria-current="page">
                        {{ page_number }}
                    </a>
                {% endfor %}

            </div>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"
                   class="min-h-[38px] min-w-[38px] py-2 px-2.5 inline-flex justify-center items-center gap-x-1.5 text-sm rounded-lg text-gray-800 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none">
                    <span>Next</span>
                    <svg class="flex-shrink-0 size-3.5" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path d="m9 18 6-6-6-6"></path>
                    </svg>
                </a>
            {% endif %}
        </div>
        <!-- End Pagination -->
    {% else %}
        <p>No reviews found.</p>
    {% endif %}
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block title %}Landing{% endblock title %}
{% block content %}
    <h1>Landing page</h1>
{% endblock content %}