books/urls.py
from django.urls import path

from books.views import BooksView, BookDetailView

app_name = "books"

urlpatterns = [
    path("", BooksView.as_view(), name="books_list"),
    path("detils/<int:year>/<int:month>/<int:day>/<slug:slug>/", BookDetailView.as_view(), name="book_detail")
]

goodreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from goodreads import settings
from goodreads.views import NotFoundView, HomeView, LandingView

handler404 = NotFoundView.as_view()


urlpatterns = [
    path("", LandingView.as_view(), name="landing"),
    path("home/", HomeView.as_view(), name="home"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),


    path("admin/", admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.utils import timezone

from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse

from books.utils import generate_unique_slug


class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    cover_picture = models.ImageField(default="default_book_cover.png")
    isbn = models.CharField(max_length=17, unique=True, blank=True, null=True)
    slug = models.SlugField(max_length=100, unique=True)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(self, self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("books:book_detail", args=[
            self.created_time.year,
            self.created_time.month,
            self.created_time.day,
            self.slug,
        ])

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(blank=True, null=True)
    bio = models.TextField(blank=True, null=True)


    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], default=0)
    created_time = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f"{self.stars_given} stars for {self.book} {self.user.username}"

books/forms.py
from django import forms

from books.models import BookReview


class AddReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ("comment", "stars_given",)

books/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.urls import reverse
from django.views.generic import ListView, DetailView

from books.forms import AddReviewForm
from books.models import Book, BookReview


# class BooksView(ListView):
#     model = Book
#     template_name = "books/index.html"
#     context_object_name = "books"


class BooksView(View):
    def get(self, request):
        book = Book.objects.all().order_by("id")

        search_query = request.GET.get("q", "")
        if search_query:
            book = book.filter(Q(title__icontains=search_query) | Q(description__icontains=search_query))

        page_size = request.GET.get("page_size", 3)
        paginator = Paginator(book, page_size)

        page_num = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_num)

        return render(request, "books/index.html", {"books": page_obj, "search_query": search_query})


# class BookDetailView(DetailView):
#     model = Book
#     template_name = "books/details.html"
#     context_object_name = "book"
#     slug_url_kwarg = 'slug'
#     query_pk_and_slug = True

class BookDetailView(View):
    def get(self, request, **kwargs):
        book = get_object_or_404(Book, slug=kwargs["slug"], created_time__year=kwargs["year"],
                                 created_time__month=kwargs["month"], created_time__day=kwargs["day"])
        review_form = AddReviewForm()
        return render(request, "books/details.html", {"book": book, "review_form": review_form})

    def post(self, request, **kwargs):
        review_form = AddReviewForm(data=request.POST)
        book = Book.objects.get(slug=kwargs["slug"])
        if review_form.is_valid():
            BookReview.objects.create(user=request.user, book=book, comment=review_form.cleaned_data["comment"],
                                stars_given=review_form.cleaned_data["stars_given"])

            return redirect(book.get_absolute_url())
            # return redirect(reverse("books:book_detail", kwargs={
            #     "slug": book.slug,
            #     "year": book.created_time.year,
            #     "month": book.created_time.month,
            #     "day": book.created_time.day
            # }))
        return render(request, "books/details.html", {"book": book, "review_form": review_form})

books/templates/books/details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Book detail{% endblock title %}
{% block content %}
    <div class="flex gap-4 my-8">
        <img class="rounded-lg border min-w-[350px] h-[500px] object-fit" src="{{ book.cover_picture.url }}"
             alt="book cover"/>
        <div>
            <h1 class="text-xl font-semibold">{{ book.title }}</h1>
            {% for book in book.bookauthor_set.all %}
                {% if forloop.first %}
                    <span class="italic text-blue-500">{{ book.author.full_name }}</span>

                {% elif forloop.last %}
                    <span class="italic text-blue-500">and {{ book.author.full_name }}</span>
                {% else %}
                    <span class="italic text-blue-500">&nbsp;{{ book.author.full_name }},</span>

                {% endif %}
            {% endfor %}
            <p>{{ book.description }}</p>
        </div>
    </div>
    <form method="post">{% csrf_token %}
        <h1 class="text-xl font-semibold my-8">Reviews:</h1>
        {{ review_form|crispy }}
        <div class="flex justify-end">
            <button class="text-white my-4 bg-blue-500 py-2 px-4 rounded">Submit</button>
        </div>
    </form>
    {% if book.bookreview_set.all.exists %}
        <h1 class="text-xl font-semibold my-8">Reviews:</h1>
        <div class="space-y-8">
            {% for review in book.bookreview_set.all reversed %}
                <div class="flex items-start">
                    <div class="flex-shrink-0">
                        <div class="inline-block relative">
                            <div class="relative w-16 h-16 rounded-full overflow-hidden">
                                <img class="absolute top-0 left-0 w-full h-full bg-cover object-fit object-cover"
                                     src="{{ review.user.profile_picture.url }}" alt="Profile picture">
                                <div class="absolute top-0 left-0 w-full h-full rounded-full shadow-inner"></div>
                            </div>
                            <svg class="fill-current text-white bg-green-600 rounded-full p-1 absolute bottom-0 right-0 w-6 h-6 -mx-1 -my-1"
                                 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path d="M19 11a7.5 7.5 0 0 1-3.5 5.94L10 20l-5.5-3.06A7.5 7.5 0 0 1 1 11V3c3.38 0 6.5-1.12 9-3 2.5 1.89 5.62 3 9 3v8zm-9 1.08l2.92 2.04-1.03-3.41 2.84-2.15-3.56-.08L10 5.12 8.83 8.48l-3.56.08L8.1 10.7l-1.03 3.4L10 12.09z"/>
                            </svg>
                        </div>
                    </div>
                    <div class="ml-6">
                        <p class="flex items-baseline">
                            <span class="text-gray-600 font-bold">{{ review.user.username }}</span>
                            <span class="ml-2 text-green-600 text-xs">Verified user</span>
                        </p>
                        <div class="flex items-center mt-1">
                            {% for _ in ''|center:5 %}
                                {% if forloop.counter <= review.stars_given %}
                                    <svg class="w-4 h-4 fill-current text-yellow-600" xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 20 20">
                                        <path d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z"/>
                                    </svg>

                                {% else %}
                                    <svg class="w-4 h-4 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 20 20">
                                        <path d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z"/>
                                    </svg>
                                {% endif %}
                            {% endfor %}


                        </div>

                        <div class="mt-3">
                            <p class="mt-1">{{ review.comment | truncatewords:100 }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    {% endif %}
{% endblock content %}

books/templates/books/index.html
{% extends "base.html" %}
{% block title %}Books{% endblock title %}
{% block content %}

    <div class="flex justify-end mb-8">
        <form method="get"
              class="bg-white flex px-4 py-3 border-b border-gray-300 focus-within:border-blue-500 overflow-hidden w-72 font-[sans-serif]">
            <button type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192.904 192.904" width="18px"
                     class="fill-gray-400 mr-3">
                    <path
                            d="m190.707 180.101-47.078-47.077c11.702-14.072 18.752-32.142 18.752-51.831C162.381 36.423 125.959 0 81.191 0 36.422 0 0 36.423 0 81.193c0 44.767 36.422 81.187 81.191 81.187 19.688 0 37.759-7.049 51.831-18.751l47.079 47.078a7.474 7.474 0 0 0 5.303 2.197 7.498 7.498 0 0 0 5.303-12.803zM15 81.193C15 44.694 44.693 15 81.191 15c36.497 0 66.189 29.694 66.189 66.193 0 36.496-29.692 66.187-66.189 66.187C44.693 147.38 15 117.689 15 81.193z">
                    </path>
                </svg>
            </button>
            <input type="text" value="{{ search_query }}" placeholder="Search..." name="q"
                   class="w-full outline-none text-sm"/>
        </form>
    </div>
    <h1 class="text-2xl mt-12 font-semibold">Books</h1>
    {% if books %}
        <div class="grid mt-6 grid-cols-5 gap-8">
            {% for book in books.object_list %}
                <a class="rounded" href="{{ book.get_absolute_url }}">
                    <img class="rounded-lg w-full h-72 object-fit" src="{{ book.cover_picture.url }}" alt="book cover"/>
                    <p class="text-center p-2 truncate">{{ book.title }}</p>
                </a>
            {% endfor %}
        </div>

        <div class="flex items-center gap-x-1 mt-8">
            {% if books.has_previous %}
                <a href="?page={{ books.previous_page_number }}"
                   class="min-h-[38px] min-w-[38px] py-2 px-2.5 inline-flex justify-center items-center gap-x-1.5 text-sm rounded-lg text-gray-800 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none"
                   disabled="">
                    <svg class="flex-shrink-0 size-3.5" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path d="m15 18-6-6 6-6"></path>
                    </svg>
                    <span>Previous</span>
                </a>
            {% endif %}

            <div class="flex items-center gap-x-1">
            
                {% for page_number in books.paginator.page_range %}
                    <a href="?page={{ page_number }}"
                       class="{% if page_number == books.number %}bg-gray-200{% endif %} min-h-[38px] min-w-[38px] flex justify-center items-center text-gray-800 py-2 px-3 text-sm rounded-lg focus:outline-none hover:bg-gray-300 disabled:opacity-50 disabled:pointer-events-none"
                       aria-current="page">
                        {{ page_number }}
                    </a>
                {% endfor %}

            </div>

            {% if books.has_next %}
                <a href="?page={{ books.next_page_number }}"
                   class="min-h-[38px] min-w-[38px] py-2 px-2.5 inline-flex justify-center items-center gap-x-1.5 text-sm rounded-lg text-gray-800 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none">
                    <span>Next</span>
                    <svg class="flex-shrink-0 size-3.5" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path d="m9 18 6-6-6-6"></path>
                    </svg>
                </a>
            {% endif %}
        </div>
        <!-- End Pagination -->
    {% else %}
        <p>No books found.</p>
    {% endif %}
{% endblock content %}